# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: LeeorNahum.Diffscroll
PackageVersion: 1.5.1
InstallerLocale: en-US
MinimumOSVersion: 10.0.17763.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- diffscroll
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/LeeorNahum/Diffscroll-Releases/releases/download/v1.5.1/Diffscroll-v1.5.1-windows-x86_64-setup.exe
  InstallerSha256: 8B26DA24422D87F9D6C9EE9A414E96DD698BBEC8F9344E11D1FEBE959B2D7F05
  ProductCode: Diffscroll
ManifestType: installer
ManifestVersion: 1.12.0
